import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import { AccessTokenProvider } from "./hoc/with-auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AccessTokenProvider>
          <div className="h-screen w-full flex flex-col">
            <div className="sticky top-0 z-10 h-[2.5em] w-full bg-primary flex items-center justify-center overflow-hidden">
              <Navbar />
            </div>
            <div className="flex-1 content-center w-full bg-secondary overflow-y-auto">
              {children}
            </div>
          </div>
        </AccessTokenProvider>
      </body>
    </html>
  );
}
